jwt:
    issuer: duki0105@gmail.com
    secret: VdmRJpYPADdk8Q7IumXgNFnbyizHtoBs
logging:
    file:
        name: log/Sboard.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        org:
            hibernate: info
            springframework:
                security: debug
        root: info
server:
    servlet:
        context-path: /
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 1234qweR!
        url: jdbc:mysql://13.124.246.53:3306/Jboard
        username: jboard
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false
    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                use_sql_comments: true
    security:
        user:
            name: user
            password: 1234
    thymeleaf:
        cache: false
        prefix: file:src/main/resources/templates/
